# Generated by Django 5.0.7 on 2024-08-08 13:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, region='IR', unique=True, verbose_name='phone number'),
        ),
    ]
